ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

# priority: higher number = higher chance of being placed

version = 16

[priorities]
"0" = 0
"1" = 1
"2" = 5
"3" = 10

[[structure]]
name = "logo"
file = "images/logo.png"
priority_file = "images/logop.png"
startx = 17
starty = 1106
priority = 3

[[structure]]
name = "skin"
file = "images/skin.png"
priority_file = "images/skinp.png"
startx = 16
starty = 1097
priority = 3
